In [ ]:

import pandas as pd

# Read the training data
train_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/06_employee/train.csv')

# Read the test data
test_data = pd.read_csv('D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/06_employee/test.csv')

# Display the first few rows of the training data
train_data.head()


Displayed on the user's machine.

In [ ]:


# Create the "YearsInCompany" feature
train_data['YearsInCompany'] = 2023 - train_data['JoiningYear']
test_data['YearsInCompany'] = 2023 - test_data['JoiningYear']

# Display the first few rows of the updated training data
train_data.head()



Displayed on the user's machine.

In [ ]:



# Encode categorical columns using one-hot encoding
train_encoded = pd.get_dummies(train_data, drop_first=True)
test_encoded = pd.get_dummies(test_data, drop_first=True)

# Display the first few rows of the encoded training data
train_encoded.head()



Displayed on the user's machine.

In [ ]:



from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report
import numpy as np

# Separate features and target variable
X_train = train_encoded.drop(columns='LeaveOrNot')
y_train = train_encoded['LeaveOrNot']
X_test = test_encoded.drop(columns='LeaveOrNot')
y_test = test_encoded['LeaveOrNot']

# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)

# Train the classifier
rf_classifier.fit(X_train, y_train)




Displayed on the user's machine.

In [ ]:



# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)
y_pred_proba = rf_classifier.predict_proba(X_test)[:, 1]

# Display the first few predictions
y_pred[:10]




array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1])

In [ ]:




# Compute the area under the ROC curve
roc_auc = roc_auc_score(y_test, y_pred_proba)

# Display the ROC AUC score
print(f"AUC-ROC: {roc_auc:.2f}")




AUC-ROC: 0.88


In [ ]:




# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print(cm)





Confusion Matrix:
[[558  52]
 [ 87 234]]


In [ ]:
Confusion Matrix:
[[558  52]
 [ 87 234]]

  Cell In[9], line 1
    Confusion Matrix:
              ^
SyntaxError: invalid syntax


In [ ]:





# Compute the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print(cm)






Confusion Matrix:
[[558  52]
 [ 87 234]]


In [ ]:

Confusion Matrix:
[[558  52]
 [ 87 234]]


  Cell In[11], line 1
    Confusion Matrix:
              ^
SyntaxError: invalid syntax


In [ ]:






# Compute the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print("TP:", cm[1, 1])
print("FP:", cm[0, 1])
print("FN:", cm[1, 0])
print("TN:", cm[0, 0])









Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558


In [ ]:

Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558


  Cell In[13], line 1
    Confusion Matrix:
              ^
SyntaxError: invalid syntax


In [ ]:







# Compute the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print("TP:", cm[1, 1])
print("FP:", cm[0, 1])
print("FN:", cm[1, 0])
print("TN:", cm[0, 0])










Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558


In [ ]:


Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558



  Cell In[15], line 1
    Confusion Matrix:
              ^
SyntaxError: invalid syntax


In [ ]:








# Compute the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print("TP:", cm[1, 1])
print("FP:", cm[0, 1])
print("FN:", cm[1, 0])
print("TN:", cm[0, 0])











Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558


In [ ]:
Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558

  Cell In[17], line 1
    Confusion Matrix:
              ^
SyntaxError: invalid syntax


In [ ]:







# Compute the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print("TP:", cm[1, 1])
print("FP:", cm[0, 1])
print("FN:", cm[1, 0])
print("TN:", cm[0, 0])










Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558


In [ ]:

Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558


  Cell In[19], line 1
    Confusion Matrix:
              ^
SyntaxError: invalid syntax


In [ ]:







# Compute the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print("TP:", cm[1, 1])
print("FP:", cm[0, 1])
print("FN:", cm[1, 0])
print("TN:", cm[0, 0])










Confusion Matrix:
TP: 234
FP: 52
FN: 87
TN: 558
