In [ ]:

import pandas as pd

# 加载训练集
train_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crime_category/train.csv'
train_data = pd.read_csv(train_path)

# 加载测试集
test_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/crime_category/test.csv'
test_data = pd.read_csv(test_path)

# 显示前几行数据以检查数据
train_data.head(), test_data.head()


(        Category  DayOfWeek PdDistrict           X          Y
 0  LARCENY/THEFT  Wednesday   SOUTHERN -122.388380  37.783310
 1   NON-CRIMINAL   Saturday   SOUTHERN -122.403405  37.775421
 2  LARCENY/THEFT  Wednesday   NORTHERN -122.419581  37.789214
 3  VEHICLE THEFT     Friday    BAYVIEW -122.389744  37.757909
 4        ASSAULT     Friday    TARAVAL -122.478377  37.742877,
          Category  DayOfWeek  PdDistrict           X          Y
 0   VEHICLE THEFT     Sunday    SOUTHERN -122.409893  37.780113
 1        BURGLARY     Monday    NORTHERN -122.424442  37.788227
 2  OTHER OFFENSES  Wednesday     BAYVIEW -122.395635  37.753565
 3        BURGLARY    Tuesday        PARK -122.444802  37.754171
 4    NON-CRIMINAL   Saturday  TENDERLOIN -122.412971  37.785788)

In [ ]:


from sklearn.preprocessing import LabelEncoder

# 初始化编码器
label_encoder = LabelEncoder()

# 对训练集和测试集中的类别变量进行编码
categorical_columns = ['DayOfWeek', 'PdDistrict']

for column in categorical_columns:
    train_data[column] = label_encoder.fit_transform(train_data[column])
    test_data[column] = label_encoder.transform(test_data[column])

# 显示预处理后的训练集和测试集的前几行
train_data.head(), test_data.head()


(        Category  DayOfWeek  PdDistrict           X          Y
 0  LARCENY/THEFT          6           7 -122.388380  37.783310
 1   NON-CRIMINAL          2           7 -122.403405  37.775421
 2  LARCENY/THEFT          6           4 -122.419581  37.789214
 3  VEHICLE THEFT          0           0 -122.389744  37.757909
 4        ASSAULT          0           8 -122.478377  37.742877,
          Category  DayOfWeek  PdDistrict           X          Y
 0   VEHICLE THEFT          3           7 -122.409893  37.780113
 1        BURGLARY          1           4 -122.424442  37.788227
 2  OTHER OFFENSES          6           0 -122.395635  37.753565
 3        BURGLARY          5           5 -122.444802  37.754171
 4    NON-CRIMINAL          2           9 -122.412971  37.785788)

In [ ]:


# 拆分训练数据
X_train = train_data.drop('Category', axis=1)
y_train = train_data['Category']

# 检查拆分后的训练数据
X_train.head(), y_train.head()


(   DayOfWeek  PdDistrict           X          Y
 0          6           7 -122.388380  37.783310
 1          2           7 -122.403405  37.775421
 2          6           4 -122.419581  37.789214
 3          0           0 -122.389744  37.757909
 4          0           8 -122.478377  37.742877,
 0    LARCENY/THEFT
 1     NON-CRIMINAL
 2    LARCENY/THEFT
 3    VEHICLE THEFT
 4          ASSAULT
 Name: Category, dtype: object)

In [ ]:


from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss

# 选择模型
model = RandomForestClassifier(n_estimators=100, random_state=42)

# 训练模型
model.fit(X_train, y_train)

# 对测试数据进行预测
X_test = test_data.drop('Category', axis=1)
y_test_pred = model.predict_proba(X_test)

# 检查预测结果
y_test_pred[:5]



array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.20878968, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.34961905, 0.        , 0.        , 0.        , 0.2220119 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.21957937, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.005     ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.0127619 , 0.        ,
        0.        , 0.17390476, 0.        , 0.        , 0.        ,
        0.67833333, 0.0775    , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.01      , 0.        , 0.01      , 0.0325    ,
        0.     

In [ ]:



# 假设测试集中的类别标签已经编码为数字
y_test = label_encoder.transform(test_data['Category'])

# 计算logloss
logloss = log_loss(y_test, y_test_pred)
logloss



---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\utils\_encode.py:235, in _encode(values, uniques, check_unknown)
    234 try:
--> 235     return _map_to_integer(values, uniques)
    236 except KeyError as e:

File D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\utils\_encode.py:174, in _map_to_integer(values, uniques)
    173 table = _nandict({val: i for i, val in enumerate(uniques)})
--> 174 return xp.asarray([table[v] for v in values], device=device(values))

File D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\utils\_encode.py:174, in <listcomp>(.0)
    173 table = _nandict({val: i for i, val in enumerate(uniques)})
--> 174 return xp.asarray([table[v] for v in values], device=device(values))

File D:\L

In [ ]:



from sklearn.preprocessing import LabelBinarizer

# 初始化编码器
label_binarizer = LabelBinarizer()

# 将训练集中的类别标签编码为二进制形式
y_train_encoded = label_binarizer.fit_transform(y_train)

# 将测试集中的类别标签编码为二进制形式，处理未见过的标签
y_test_encoded = label_binarizer.transform(test_data['Category'])

# 检查编码后的标签
y_train_encoded[:5], y_test_encoded[:5]



(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0

In [ ]:



# 重新训练模型
model.fit(X_train, y_train_encoded)

# 对测试数据进行预测
y_test_pred = model.predict_proba(X_test)

# 检查预测结果
y_test_pred[:5]




[array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]),
 array([[1.        , 0.        ],
        [1.        , 0.        ],
        [1.        , 0.        ],
        ...,
        [0.85021695, 0.14978305],
        [1.        , 0.        ],
        [0.97166667, 0.02833333]]),
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]),
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]),
 array([[1.        , 0.        ],
        [0.98666667, 0.01333333],
        [0.68505615, 0.31494385],
        ...,
        [1.        , 0.        ],
        [1.        , 0.        ],
        [0.99      , 0.01      ]])]

In [ ]:


import numpy as np

# 拼接预测结果
y_test_pred_combined = np.hstack(y_test_pred)

# 检查拼接后的预测结果
y_test_pred_combined[:5]



Output truncated. Showing the last 2800 characters. You should try again and use computer.ai.summarize(output) over the output, or break it down into smaller steps.

       , 0.        , 1.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 0.89168339, 0.10831661, 1.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ,
        1.        , 0.        , 1.        , 0.        , 0.87096155,
        0.12903845, 1.        , 0.        , 1.        , 0.        ,
        0.78327364, 0.21672636, 0.88482735, 0.11517265],
       [1.        , 0.        , 0.97833333, 0.021666

In [ ]:



# 计算logloss
logloss = log_loss(y_test_encoded, y_test_pred_combined)
logloss




D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\metrics\_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 4
      2 pass
      3 print('##active_line2##')
----> 4 logloss = log_loss(y_test_encoded, y_test_pred_combined)
      5 print('##active_line3##')
      6 logloss

File D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\utils\_param_validation.py:216, in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    210 try:
    211     with config_context(
    212         skip_parameter_validation=(
    213             prefer_skip_nested_validation or global_skip_validation
    214         )
    215     ):
--> 216         return func(*args, **kwarg

In [ ]:



# 检查 y_train_encoded 和 y_test_encoded 的形状
y_train_encoded.shape, y_test_encoded.shape




((70244, 37), (17560, 37))

In [ ]:



# 重新检查 y_test_pred 的形状
for i, pred in enumerate(y_test_pred):
    print(f"Shape of y_test_pred[{i}]: {pred.shape}")

# 确保拼接后的预测结果形状正确
y_test_pred_combined = np.hstack(y_test_pred)

# 检查拼接后的预测结果的形状
y_test_pred_combined.shape





Shape of y_test_pred[0]: (17560, 2)
Shape of y_test_pred[1]: (17560, 2)
Shape of y_test_pred[2]: (17560, 2)
Shape of y_test_pred[3]: (17560, 2)
Shape of y_test_pred[4]: (17560, 2)
Shape of y_test_pred[5]: (17560, 2)
Shape of y_test_pred[6]: (17560, 2)
Shape of y_test_pred[7]: (17560, 2)
Shape of y_test_pred[8]: (17560, 2)
Shape of y_test_pred[9]: (17560, 2)
Shape of y_test_pred[10]: (17560, 2)
Shape of y_test_pred[11]: (17560, 2)
Shape of y_test_pred[12]: (17560, 2)
Shape of y_test_pred[13]: (17560, 2)
Shape of y_test_pred[14]: (17560, 2)
Shape of y_test_pred[15]: (17560, 2)
Shape of y_test_pred[16]: (17560, 2)
Shape of y_test_pred[17]: (17560, 2)
Shape of y_test_pred[18]: (17560, 2)
Shape of y_test_pred[19]: (17560, 2)
Shape of y_test_pred[20]: (17560, 2)
Shape of y_test_pred[21]: (17560, 2)
Shape of y_test_pred[22]: (17560, 2)
Shape of y_test_pred[23]: (17560, 2)
Shape of y_test_pred[24]: (17560, 2)
Shape of y_test_pred[25]: (17560, 2)
Shape of y_test_pred[26]: (17560, 2)
Shape of y_

In [ ]:




# 重新组织预测结果
y_test_pred_reshaped = np.concatenate(y_test_pred, axis=1)[:, :37]

# 检查重新组织后的预测结果的形状
y_test_pred_reshaped.shape





(17560, 37)

In [ ]:




# 计算logloss
logloss = log_loss(y_test_encoded, y_test_pred_reshaped)
logloss





D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\metrics\_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
15.82880550793803

In [ ]:




# 保存预测结果到文件
np.savetxt('test_predictions.csv', y_test_pred_reshaped, delimiter=',')

# 打印保存成功的消息
print("预测结果已保存到 test_predictions.csv 文件中。")


预测结果已保存到 test_predictions.csv 文件中。
