In [ ]:

import pandas as pd

# Load the datasets
train_data_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/04_diabetes/train.csv'
test_data_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark/DSEval/datasets/04_diabetes/test.csv'

train_df = pd.read_csv(train_data_path)
test_df = pd.read_csv(test_data_path)

# Drop duplicate rows
train_df = train_df.drop_duplicates()
test_df = test_df.drop_duplicates()

# Print the shapes to ensure duplicates are dropped
print(f"Training data shape: {train_df.shape}")
print(f"Test data shape: {test_df.shape}")

# Show the first few rows of the datasets
print(train_df.head())
print(test_df.head())


Training data shape: (77430, 9)
Test data shape: (19807, 9)
   gender   age  hypertension  ...  HbA1c_level blood_glucose_level  diabetes
0    Male  73.0             0  ...          3.5                  80         0
1    Male  80.0             0  ...          5.7                 145         1
2  Female  38.0             0  ...          4.0                 158         0
3  Female  26.0             0  ...          5.0                 100         0
4  Female  61.0             1  ...          4.5                  85         0

[5 rows x 9 columns]
   gender   age  hypertension  ...  HbA1c_level blood_glucose_level  diabetes
0  Female  13.0             0  ...          5.8                 126         0
1  Female   3.0             0  ...          5.0                 145         0
2    Male  63.0             0  ...          3.5                 200         0
3  Female   2.0             0  ...          6.1                 126         0
4  Female  33.0             0  ...          6.2             

In [ ]:

# One-hot encode the "gender" and "smoking_history" columns
train_df_encoded = pd.get_dummies(train_df, columns=['gender', 'smoking_history'])
test_df_encoded = pd.get_dummies(test_df, columns=['gender', 'smoking_history'])

# Print the shapes to ensure encoding is done correctly
print(f"Training data shape after encoding: {train_df_encoded.shape}")
print(f"Test data shape after encoding: {test_df_encoded.shape}")

# Show the first few rows of the encoded datasets
print(train_df_encoded.head())
print(test_df_encoded.head())



Training data shape after encoding: (77430, 16)
Test data shape after encoding: (19807, 16)
    age  hypertension  ...  smoking_history_never  smoking_history_not current
0  73.0             0  ...                  False                        False
1  80.0             0  ...                   True                        False
2  38.0             0  ...                  False                        False
3  26.0             0  ...                  False                         True
4  61.0             1  ...                  False                        False

[5 rows x 16 columns]
    age  hypertension  ...  smoking_history_never  smoking_history_not current
0  13.0             0  ...                  False                        False
1   3.0             0  ...                  False                        False
2  63.0             0  ...                  False                        False
3   2.0             0  ...                   True                        False
4  33.0         

In [ ]:


import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

# Define the features and target variable
X_train = train_df_encoded.drop('diabetes', axis=1)
y_train = train_df_encoded['diabetes']

# Initialize and fit the Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Get feature importances
feature_importances = pd.Series(rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)

# Print the feature importances
print(feature_importances)




HbA1c_level                    0.407970
blood_glucose_level            0.312457
bmi                            0.125713
age                            0.105406
hypertension                   0.015265
heart_disease                  0.010795
smoking_history_No Info        0.003989
smoking_history_former         0.003733
smoking_history_never          0.003394
smoking_history_current        0.002612
gender_Male                    0.002222
gender_Female                  0.002198
smoking_history_not current    0.002194
smoking_history_ever           0.002050
gender_Other                   0.000002
dtype: float64


In [ ]:



# Initialize and fit the Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf.fit(X_train, y_train)

# Prepare the test set
X_test = test_df_encoded.drop('diabetes', axis=1)
y_test = test_df_encoded['diabetes']

# Make predictions on the test set
y_pred = rf.predict(X_test)

# Print the predictions
print(y_pred)




[0 0 0 ... 0 0 0]


In [ ]:




from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

# Compute the probability estimates for the positive class
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# Compute the AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC: {auc_roc}")

# Show the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")

# Show the classification report
cr = classification_report(y_test, y_pred)
print(f"Classification Report:\n{cr}")




AUC-ROC: 0.9647247192225222
Confusion Matrix:
[[18023    76]
 [  533  1175]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     18099
           1       0.94      0.69      0.79      1708

    accuracy                           0.97     19807
   macro avg       0.96      0.84      0.89     19807
weighted avg       0.97      0.97      0.97     19807



In [ ]:
 ```
   [[18023    76]
    [  533  1175]]
  

  Cell In[7], line 1
    ```
    ^
SyntaxError: invalid syntax


In [ ]:

from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

# Compute the probability estimates for the positive class
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# Compute the AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC: {auc_roc}")

# Show the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Show the classification report
cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)


AUC-ROC: 0.9647247192225222
Confusion Matrix:
[[18023    76]
 [  533  1175]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     18099
           1       0.94      0.69      0.79      1708

    accuracy                           0.97     19807
   macro avg       0.96      0.84      0.89     19807
weighted avg       0.97      0.97      0.97     19807



In [ ]:
precision    recall  f1-score   support

           0       0.97      1.00      0.98     18099
           1       0.94      0.69

  Cell In[9], line 1
    precision    recall  f1-score   support
                 ^
SyntaxError: invalid syntax


In [ ]:


from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

# Compute the probability estimates for the positive class
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# Compute the AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC: {auc_roc}")

# Show the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Show the classification report
cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)



AUC-ROC: 0.9647247192225222
Confusion Matrix:
[[18023    76]
 [  533  1175]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     18099
           1       0.94      0.69      0.79      1708

    accuracy                           0.97     19807
   macro avg       0.96      0.84      0.89     19807
weighted avg       0.97      0.97      0.97     19807



In [ ]:
[[18023    76]
 [  533  1175]]

  Cell In[11], line 1
    [[18023    76]
      ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?


In [ ]:





from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

# Compute the probability estimates for the positive class
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# Compute the AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC: {auc_roc}")

# Show the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Show the classification report
cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)




AUC-ROC: 0.9647247192225222
Confusion Matrix:
[[18023    76]
 [  533  1175]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     18099
           1       0.94      0.69      0.79      1708

    accuracy                           0.97     19807
   macro avg       0.96      0.84      0.89     19807
weighted avg       0.97      0.97      0.97     19807



In [ ]:
 ```
   [[18023    76]
    [  533  1175]]
  

  Cell In[13], line 1
    ```
    ^
SyntaxError: invalid syntax


In [ ]:



from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

# Compute the probability estimates for the positive class
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# Compute the AUC-ROC
auc_roc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC: {auc_roc}")

# Show the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Show the classification report
cr = classification_report(y_test, y_pred)
print("Classification Report:")
print(cr)




AUC-ROC: 0.9647247192225222
Confusion Matrix:
[[18023    76]
 [  533  1175]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     18099
           1       0.94      0.69      0.79      1708

    accuracy                           0.97     19807
   macro avg       0.96      0.84      0.89     19807
weighted avg       0.97      0.97      0.97     19807

