In [ ]:

import pandas as pd

# Define the path to the train dataset
file_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/obesity_CVD_risk/train.csv'

# Load the data
train_data = pd.read_csv(file_path)

# Display the first few rows of the dataset
train_data.head()


Displayed on the user's machine.

In [ ]:


# Display basic statistics of the dataset
train_data.describe()

# Check for missing values
missing_values = train_data.isnull().sum()

missing_values, train_data.shape



(id                                0
 Gender                            0
 Age                               0
 Height                            0
 Weight                            0
 family_history_with_overweight    0
 FAVC                              0
 FCVC                              0
 NCP                               0
 CAEC                              0
 SMOKE                             0
 CH2O                              0
 SCC                               0
 FAF                               0
 TUE                               0
 CALC                              0
 MTRANS                            0
 NObeyesdad                        0
 dtype: int64,
 (16606, 18))

In [ ]:


from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# List of categorical columns to encode
categorical_columns = [
    'Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE', 'CALC', 'MTRANS', 'NObeyesdad'
]

# Encode categorical columns
for column in categorical_columns:
    train_data[column] = label_encoder.fit_transform(train_data[column])

# Display the first few rows of the dataset after encoding
train_data.head()


Displayed on the user's machine.

In [ ]:


from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# List of numerical columns to scale
numerical_columns = ['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']

# Scale numerical columns
train_data[numerical_columns] = scaler.fit_transform(train_data[numerical_columns])

# Display the first few rows of the dataset after scaling
train_data.head()



Displayed on the user's machine.

In [ ]:



from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = train_data.drop(columns=['id', 'NObeyesdad'])
y = train_data['NObeyesdad']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
X_train.shape, X_val.shape, y_train.shape, y_val.shape




((13284, 16), (3322, 16), (13284,), (3322,))

In [ ]:



from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialize the RandomForestClassifier
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the validation set
y_pred = model.predict(X_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, y_pred)

accuracy




Output truncated. Showing the last 2800 characters. You should try again and use computer.ai.summarize(output) over the output, or break it down into smaller steps.

   )
   1368 ensure_all_finite = _deprecate_force_all_finite(force_all_finite, ensure_all_finite)
-> 1370 X = check_array(
   1371     X,
   1372     accept_sparse=accept_sparse,
   1373     accept_large_sparse=accept_large_sparse,
   1374     dtype=dtype,
   1375     order=order,
   1376     copy=copy,
   1377     force_writeable=force_writeable,
   1378     ensure_all_finite=ensure_all_finite,
   1379     ensure_2d=ensure_2d,
   1380     allow_nd=allow_nd,
   1381     ensure_min_samples=ensure_min_samples,
   1382     ensure_min_features=ensure_min_features,
   1383     estimator=estimator,
   1384     input_name="X",
   1385 )
   1387 y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
   1389 check_consistent_length(X, y)

File D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter

In [ ]:


# Check the unique values in the 'SCC' column
train_data['SCC'].unique()

# Encode the 'SCC' column
train_data['SCC'] = label_encoder.fit_transform(train_data['SCC'])

# Display the unique values in the 'SCC' column after encoding
train_data['SCC'].unique()


array([0, 1])

In [ ]:



# Redefine features (X) and target (y) after encoding 'SCC'
X = train_data.drop(columns=['id', 'NObeyesdad'])
y = train_data['NObeyesdad']

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
X_train.shape, X_val.shape, y_train.shape, y_val.shape




((13284, 16), (3322, 16), (13284,), (3322,))

In [ ]:




# Initialize the RandomForestClassifier
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the validation set
y_pred = model.predict(X_val)

# Calculate accuracy
accuracy = accuracy_score(y_val, y_pred)

accuracy





0.8925346177001806

In [ ]:



# Define the path to the test dataset
test_file_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/obesity_CVD_risk/test.csv'

# Load the test data
test_data = pd.read_csv(test_file_path)

# Display the first few rows of the test dataset
test_data.head()




Displayed on the user's machine.

In [ ]:




# Initialize the LabelEncoder for test data
label_encoder = LabelEncoder()

# List of categorical columns to encode
categorical_columns = [
    'Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE', 'CALC', 'MTRANS', 'NObeyesdad', 'SCC'
]

# Encode categorical columns in the test data
for column in categorical_columns:
    test_data[column] = label_encoder.fit_transform(test_data[column])

# Scale numerical columns in the test data
test_data[numerical_columns] = scaler.transform(test_data[numerical_columns])

# Display the first few rows of the test dataset after preprocessing
test_data.head()



Displayed on the user's machine.

In [ ]:



# Define features (X_test) and target (y_test) for the test dataset
X_test = test_data.drop(columns=['id', 'NObeyesdad'])
y_test = test_data['NObeyesdad']

# Make predictions on the test set
y_pred_test = model.predict(X_test)

# Calculate accuracy on the test set
accuracy_test = accuracy_score(y_test, y_pred_test)

accuracy_test, y_pred_test[:5]  # Display the accuracy and the first 5 predictions




(0.894990366088632, array([4, 5, 2, 3, 0]))

In [ ]:




# Map the predicted labels back to their original categories
predicted_labels = label_encoder.inverse_transform(y_pred_test)

# Display the first 5 predicted labels
predicted_labels[:5]





---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[14], line 4
      2 pass
      3 print('##active_line2##')
----> 4 predicted_labels = label_encoder.inverse_transform(y_pred_test)
      5 print('##active_line3##')
      6 pass

File D:\LLM-Driven_AI-Studio\MLAgent\experiments\OpenInterpreter\venv\lib\site-packages\sklearn\preprocessing\_label.py:162, in LabelEncoder.inverse_transform(self, y)
    156 diff = _setdiff1d(
    157     ar1=y,
    158     ar2=xp.arange(self.classes_.shape[0], device=device(y)),
    159     xp=xp,
    160 )
    161 if diff.shape[0]:
--> 162     raise ValueError("y contains previously unseen labels: %s" % str(diff))
    163 y = xp.asarray(y)
    164 return xp.take(self.classes_, y, axis=0)

ValueError: y contains previously unseen labels: [2 3 4 5 6]

In [ ]:




# Check the classes learned by the LabelEncoder
label_encoder.classes_





array(['no', 'yes'], dtype=object)

In [ ]:




# Initialize a new LabelEncoder for the NObeyesdad column
nobeyesdad_encoder = LabelEncoder()

# Fit the encoder on the NObeyesdad column in the training data
nobeyesdad_encoder.fit(train_data['NObeyesdad'])

# Encode the NObeyesdad column in both the training and test data
train_data['NObeyesdad'] = nobeyesdad_encoder.transform(train_data['NObeyesdad'])
test_data['NObeyesdad'] = nobeyesdad_encoder.transform(test_data['NObeyesdad'])

# Check the unique values in the NObeyesdad column after encoding
nobeyesdad_encoder.classes_





array([0, 1, 2, 3, 4, 5, 6])

In [ ]:





# Redefine features (X_train) and target (y_train) for the training dataset
X_train = train_data.drop(columns=['id', 'NObeyesdad'])
y_train = train_data['NObeyesdad']

# Redefine features (X_test) and target (y_test) for the test dataset
X_test = test_data.drop(columns=['id', 'NObeyesdad'])
y_test = test_data['NObeyesdad']

# Reinitialize and train the RandomForestClassifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_test = model.predict(X_test)

# Calculate accuracy on the test set
accuracy_test = accuracy_score(y_test, y_pred_test)

accuracy_test, y_pred_test[:5]  # Display the accuracy and the first 5 predictions






(0.8959537572254336, array([4, 5, 2, 3, 1]))

In [ ]:





# Map the predicted labels back to their original categories
predicted_labels = nobeyesdad_encoder.inverse_transform(y_pred_test)

# Display the first 5 predicted labels
predicted_labels[:5]






array([4, 5, 2, 3, 1])

In [ ]:




# Display the first 5 predicted labels with their corresponding category names
nobeyesdad_encoder.inverse_transform([4, 5, 2, 3, 1])





array([4, 5, 2, 3, 1])

In [ ]:





# Display the classes learned by the LabelEncoder
nobeyesdad_encoder.classes_

# Map the first 5 predicted labels back to their original categories
predicted_labels_names = [nobeyesdad_encoder.classes_[label] for label in y_pred_test[:5]]

predicted_labels_names






[np.int64(4), np.int64(5), np.int64(2), np.int64(3), np.int64(1)]

In [ ]:





# Display the classes learned by the LabelEncoder
nobeyesdad_classes = nobeyesdad_encoder.classes_

# Map the first 5 predicted labels back to their original categories
predicted_labels_names = [nobeyesdad_classes[label] for label in y_pred_test[:5]]

predicted_labels_names






[np.int64(4), np.int64(5), np.int64(2), np.int64(3), np.int64(1)]