In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_log_error
import os


In [ ]:

# Define the file path
file_path = r'D:\LLM-Driven_AI-Studio\MLAgent\data\benchmark/NL2Workflow/datasets/tabular/abalone/train.csv'

# Load the data
data = pd.read_csv(file_path)

# Display the first few rows of the dataset
print(data.head())


      id Sex  Length  ...  Whole weight.2  Shell weight  Rings
0  43718   M   0.650  ...          0.3020         0.360     10
1  45247   F   0.670  ...          0.3455         0.385     11
2  71393   M   0.605  ...          0.2470         0.285      9
3  51688   M   0.680  ...          0.3060         0.440     11
4  40681   I   0.295  ...          0.0190         0.038      5

[5 rows x 10 columns]


In [ ]:


# Check for missing values
print(data.isnull().sum())

# Convert the 'Sex' column to categorical variables
data = pd.get_dummies(data, columns=['Sex'], drop_first=True)

# Display the first few rows of the preprocessed dataset
print(data.head())



id                0
Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Whole weight.1    0
Whole weight.2    0
Shell weight      0
Rings             0
dtype: int64
      id  Length  Diameter  Height  ...  Shell weight  Rings  Sex_I  Sex_M
0  43718   0.650     0.505   0.175  ...         0.360     10  False   True
1  45247   0.670     0.520   0.195  ...         0.385     11  False  False
2  71393   0.605     0.495   0.150  ...         0.285      9  False   True
3  51688   0.680     0.560   0.200  ...         0.440     11  False   True
4  40681   0.295     0.200   0.075  ...         0.038      5   True  False

[5 rows x 11 columns]


In [ ]:


# Select features and target variable
features = data.drop(columns=['id', 'Whole weight', 'Whole weight.1', 'Whole weight.2', 'Rings'])
target = data['Rings']

# Display the first few rows of the selected features
print(features.head())


   Length  Diameter  Height  Shell weight  Sex_I  Sex_M
0   0.650     0.505   0.175         0.360  False   True
1   0.670     0.520   0.195         0.385  False  False
2   0.605     0.495   0.150         0.285  False   True
3   0.680     0.560   0.200         0.440  False   True
4   0.295     0.200   0.075         0.038   True  False


In [ ]:


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Display the size of the training and testing sets
print(f"Training set size: {X_train.shape}")
print(f"Testing set size: {X_test.shape}")



Training set size: (57993, 6)
Testing set size: (14499, 6)


In [ ]:



# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Display the first few rows of the scaled features
print(X_train_scaled[:5])




[[ 0.57387598  0.79863491 -0.01440923 -0.05389259 -0.75746847  1.38577947]
 [-0.35761386 -0.52866288 -0.53961055 -0.76905214  1.32018697 -0.72161554]
 [ 0.19281196  0.23708585 -0.01440923  0.18449393 -0.75746847 -0.72161554]
 [ 0.53153553  0.49233542  0.64209241  0.2613928  -0.75746847  1.38577947]
 [ 0.36217374  0.49233542  0.64209241  0.33829168 -0.75746847  1.38577947]]


In [ ]:



# Initialize the SVR model
svr_model = SVR(kernel='rbf')

# Train the model
svr_model.fit(X_train_scaled, y_train)

# Display the training status
print("Model training completed.")




Model training completed.


In [ ]:




# Predict the rings (age) on the test set
y_pred = svr_model.predict(X_test_scaled)

# Ensure all predictions are positive (since Rings represent age, which cannot be negative)
y_pred = np.maximum(y_pred, 1e-6)

# Calculate RMLSE
rmlse = np.sqrt(mean_squared_log_error(y_test, y_pred))

# Display the RMLSE
print(f"RMLSE: {rmlse}")




RMLSE: 0.16573969821988974
