In [ ]:

import pandas as pd

# Load the training and test datasets
train_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\DSEval\\datasets\\06_employee\\train.csv'
test_path = 'D:\\LLM-Driven_AI-Studio\\MLAgent\\data\\benchmark\\DSEval\\datasets\\06_employee\\test.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Display the first few rows of the training and test datasets
train_df.head(), test_df.head()


(   Education  JoiningYear  ... ExperienceInCurrentDomain  LeaveOrNot
 0    Masters         2013  ...                         0           1
 1  Bachelors         2012  ...                         3           0
 2    Masters         2017  ...                         2           0
 3    Masters         2012  ...                         2           0
 4    Masters         2017  ...                         2           0
 
 [5 rows x 9 columns],
    Education  JoiningYear  ... ExperienceInCurrentDomain  LeaveOrNot
 0  Bachelors         2016  ...                         2           1
 1  Bachelors         2013  ...                         4           0
 2  Bachelors         2017  ...                         3           1
 3    Masters         2015  ...                         2           0
 4  Bachelors         2012  ...                         1           0
 
 [5 rows x 9 columns])

In [ ]:


# Add a new feature 'YearsInCompany' to both the training and test datasets
train_df['YearsInCompany'] = 2023 - train_df['JoiningYear']
test_df['YearsInCompany'] = 2023 - test_df['JoiningYear']

# Display the first few rows of the datasets with the new feature
train_df.head(), test_df.head()



(   Education  JoiningYear  ... LeaveOrNot  YearsInCompany
 0    Masters         2013  ...          1              10
 1  Bachelors         2012  ...          0              11
 2    Masters         2017  ...          0               6
 3    Masters         2012  ...          0              11
 4    Masters         2017  ...          0               6
 
 [5 rows x 10 columns],
    Education  JoiningYear  ... LeaveOrNot  YearsInCompany
 0  Bachelors         2016  ...          1               7
 1  Bachelors         2013  ...          0              10
 2  Bachelors         2017  ...          1               6
 3    Masters         2015  ...          0               8
 4  Bachelors         2012  ...          0              11
 
 [5 rows x 10 columns])

In [ ]:


# Perform one-hot encoding on the categorical columns
categorical_columns = ['Education', 'City', 'Gender', 'EverBenched']

train_df_encoded = pd.get_dummies(train_df, columns=categorical_columns)
test_df_encoded = pd.get_dummies(test_df, columns=categorical_columns)

# Display the first few rows of the encoded datasets
train_df_encoded.head(), test_df_encoded.head()



(   JoiningYear  PaymentTier  Age  ...  Gender_Male  EverBenched_No  EverBenched_Yes
 0         2013            3   30  ...         True            True            False
 1         2012            3   25  ...         True            True            False
 2         2017            2   29  ...         True            True            False
 3         2012            3   24  ...         True            True            False
 4         2017            2   35  ...         True            True            False
 
 [5 rows x 16 columns],
    JoiningYear  PaymentTier  Age  ...  Gender_Male  EverBenched_No  EverBenched_Yes
 0         2016            3   24  ...        False            True            False
 1         2013            3   26  ...        False            True            False
 2         2017            2   25  ...        False            True            False
 3         2015            2   28  ...        False            True            False
 4         2012            3   33  ... 

In [ ]:



from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix

# Split the training data into features (X) and target variable (y)
X_train = train_df_encoded.drop(columns=['LeaveOrNot', 'JoiningYear'])
y_train = train_df_encoded['LeaveOrNot']

# Split the test data into features (X) and target variable (y)
X_test = test_df_encoded.drop(columns=['LeaveOrNot', 'JoiningYear'])
y_test = test_df_encoded['LeaveOrNot']

# Initialize and train the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)
y_pred_proba = rf_classifier.predict_proba(X_test)[:, 1]

# Display the first few predictions
y_pred[:5], y_pred_proba[:5]




(array([0, 0, 0, 0, 0]),
 array([0.03611723, 0.        , 0.01      , 0.04      , 0.17833333]))

In [ ]:




# Compute the area under the ROC curve
roc_auc = roc_auc_score(y_test, y_pred_proba)
roc_auc


np.float64(0.8798656861243042)

In [ ]:




# Compute the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
conf_matrix



array([[557,  53],
       [ 86, 235]])